### ISSUE TITLE
Create a travis.yml

### ISSUE THREAD

**Issue by prasadtalasila** [AutolabJS/containers#1]
Create travis.yml using [this template](https://github.com/docker-library/mysql/blob/master/.travis.yml)

**Comment by prasadtalasila** [comment]
@jineetd please work on this issue next. In case of any queries, please raise questions on gitter channel.

**Comment by prasadtalasila** [comment]
Relevant help is available at:
1. [xenial build environment](https://docs.travis-ci.com/user/reference/xenial/)
1. [travis job build lifecycle](https://docs.travis-ci.com/user/job-lifecycle/)
1. [travis build notifications](https://docs.travis-ci.com/user/notifications/)

**Comment by prasadtalasila** [comment]
A tentative `.travis.yml` file:
```
sudo: required
dist: xenial

notifications:
  email:
    recipients:
      - kaushikrohit325@gmail.com
      - prasad.talasila@eng.au.dk
    on_success: change
    on_failure: always

script:
- bash tests/test_runner.sh
```
